build:
  dependencies:
    override:
      - pip install -r req-scrutinizer.txt
  tests:
    override:
      - flake8 --filename=* bin
      - python theano/tests/test_flake8.py Theano/theano
checks:
    python:
        code_rating: true
        duplicate_code: true
        format_bad_indentation:
            indentation: '4 spaces'
        format_mixed_indentation: true
        format_line_too_long:
            max_length: '79'
        imports_relative_import: true
        imports_wildcard_import: true
        format_bad_whitespace: true
        format_multiple_statements: true
        basic_invalid_name:
            functions: '[a-z_][a-z0-9_]{0,30}$'
            variables: '(([a-z_][a-z0-9_]{0,30})|(_?[A-Z]))$'
            whitelisted_names: '_,floatX,logger,config'
            constants: '(([A-Z_][A-Z0-9_]*)|(__.*__))$'
            attributes: '(([a-z_][a-z0-9_]{0,30})|(_?[A-Z]))$'
            arguments: '(([a-z_][a-z0-9_]{0,30})|(_?[A-Z]))$'
            class_attributes: '([A-Za-z_][A-Za-z0-9_]{0,30}|(__.*__))$'
            inline_vars: '[A-Za-z_][A-Za-z0-9_]*$'
            classes: '[A-Z_][a-zA-Z0-9]+$'
            modules: '(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$'
            methods: '[a-z_][a-z0-9_]{0,30}$'
        classes_no_self_argument: true
        classes_bad_mcs_method_argument: true
        classes_bad_classmethod_argument: true
        variables_unused_variable: true
        variables_unused_import: true
        variables_used_before_assignment: true
        variables_undefined_variable: true
        variables_undefined_loop_variable: true
        variables_redefined_outer_name: true
        variables_redefined_builtin: true
        variables_redefine_in_handler: true
        variables_no_name_in_module: true
        variables_global_variable_undefined: true
        variables_global_variable_not_assigned: true
        variables_global_statement: true
        typecheck_unexpected_keyword_arg: true
        variables_global_at_module_level: true
        variables_unused_wildcard_import: true
        variables_unused_argument: true
        variables_unpacking_non_sequence: true
        variables_undefined_all_variable: true
        variables_unbalanced_tuple_unpacking: true
        variables_invalid_all_object: true
        typecheck_too_many_function_args: true
        typecheck_redundant_keyword_arg: true
        typecheck_not_callable: true
        typecheck_no_member: true
        typecheck_missing_kwoa: true
        typecheck_maybe_no_member: true
        typecheck_duplicate_keyword_arg: true
        typecheck_assignment_from_none: true
        typecheck_assignment_from_no_return: true
        string_unused_format_string_key: true
        string_truncated_format_string: true
        string_too_many_format_args: true
        string_too_few_format_args: true
        string_mixed_format_string: true
        string_missing_format_string_key: true
        string_format_needs_mapping: true
        string_constant_anomalous_unicode_escape_in_string: true
        string_constant_anomalous_backslash_in_string: true
        string_bad_str_strip_call: true
        string_bad_format_string_key: true
        string_bad_format_character: true
        open_mode_bad_open_mode: true
        newstyle_bad_super_call: true
        logging_unsupported_format: true
        logging_too_many_args: true
        logging_too_few_args: true
        logging_not_lazy: true
        logging_format_truncated: true
        imports_reimported: true
        imports_import_self: true
        imports_deprecated_module: true
        imports_cyclic_import: true
        format_unnecessary_semicolon: true
        format_trailing_whitespace: true
        format_superfluous_parens: true
        format_old_ne_operator: true
        format_missing_final_newline: true
        format_lowercase_l_suffix: true
        format_backtick: true
        exceptions_raising_string: true
        exceptions_raising_non_exception: true
        exceptions_raising_bad_type: true
        exceptions_pointless_except: true
        exceptions_notimplemented_raised: true
        exceptions_catching_non_exception: true
        exceptions_broad_except: true
        exceptions_binary_op_exception: true
        exceptions_bare_except: true
        exceptions_bad_except_order: true
        design_interface_not_implemented: true
        design_abstract_class_not_used: true
        design_abstract_class_little_used: true
        classes_valid_slots: true
        classes_super_init_not_called: true
        classes_signature_differs: true
        classes_protected_access: true
        classes_non_parent_init_called: true
        classes_non_iterator_returned: true
        classes_no_method_argument: true
        classes_no_method_argument: true
        classes_no_init: true
        classes_missing_interface_method: true
        classes_method_hidden: true
        classes_interface_is_not_class: true
        classes_bad_staticmethod_argument: true
        classes_bad_mcs_classmethod_argument: true
        classes_bad_context_manager: true
        classes_arguments_differ: true
        classes_access_member_before_definition: true
        basic_yield_outside_function: true
        basic_useless_else_on_loop: true
        basic_unreachable: true
        basic_unnecessary_pass: true
        basic_unnecessary_lambda: true
        basic_return_outside_function: true
        basic_return_in_init: true
        basic_return_arg_in_generator: true
        basic_pointless_string_statement: true
        basic_pointless_statement: true
        basic_old_raise_syntax: true
        basic_not_in_loop: true
        basic_nonexistent_operator: true
        basic_missing_reversed_argument: true
        basic_missing_module_attribute: true
        basic_lost_exception: true
        basic_init_is_generator: true
        basic_function_redefined: true
        basic_expression_not_assigned: true
        basic_exec_used: true
        basic_eval_used: true
        basic_empty_docstring: true
        basic_duplicate_key: true
        basic_duplicate_argument_name: true
        basic_dangerous_default_value: true
        basic_bad_reversed_sequence: true
        basic_assert_on_tuple: true
        basic_abstract_class_instantiated: true
filter:
    paths:
        - blocks/*
        - bin/*
