#!/usr/bin/python
#
# Call the command line interface for Epydoc.
#

# Make sure that we don't get confused between an epydoc.py script and
# the real epydoc package.
import sys, os.path
if os.path.exists(os.path.join(sys.path[0], 'epydoc.py')):
    del sys.path[0]

from epydoc import docintrospecter 
from epydoc.apidoc import RoutineDoc

def specialize_to_RoutineDoc(value, value_doc, module_name):
    value_doc.specialize_to(RoutineDoc)

docintrospecter.register_introspecter(
        lambda value: getattr(value, '__epydoc_asRoutine', False), 
        specialize_to_RoutineDoc, 
        priority=-1)

from epydoc.cli import cli
cli()

