#!/usr/bin/python
#
# Call the command line interface for Epydoc.
#

# Make sure that we don't get confused between an epydoc.py script and
# the real epydoc package.
import sys, os.path
if os.path.exists(os.path.join(sys.path[0], 'epydoc.py')):
    del sys.path[0]

from epydoc import docintrospecter 
from epydoc.apidoc import RoutineDoc

from theano.gof import Op

def applicability_test(value):
    return isinstance(value, Op)

def introspecter(value, value_doc, module_name):
    value_doc.specialize_to(RoutineDoc)
#     print value
#     try:
#         value_doc.specialize_to(RoutineDoc)
#         print 'Yay!', value
#     except:
# 	print value

docintrospecter.register_introspecter(applicability_test, introspecter, priority=-1)

from epydoc.cli import cli
cli()

